# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a4a2379805ddc131ad2e66b06286f3a06a6022d29d6d02f0db5faab1cb9bb15fb3226ff43b76becc155f8599e1ff7b32b4a8704fec0915741ee2f2fe4a95d2c

test:
  secret_key_base: 6515e106cf1d85c667c987d27f10619c745bdfa9458d31ed828fc8168c76764129a1844d503953a10c0b1d3611489215e0a919ce2d9e4baeda5a6f86c2650779

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
